version: "3"

services:
  db:
    image: postgres
    restart: always
    container_name: alpha-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_name
    ports:
      - "5432:5432"
    volumes:
      - project_name_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: alpha-tracker-app
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
    ports:
      - "8080:8080"
    command: sh -c "alembic upgrade head && uvicorn project_name.main:app --host 0.0.0.0 --port 8080"

  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    container_name: alpha-tracker-web
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - INTERNAL_URL=http://backend:8080
    command: npm start

volumes:
  project_name_db_data:
